source 'https://github.com/CocoaPods/Specs'

target 'Reach Sample' do
  platform :ios, '12.2'
  use_frameworks!
  
  pod 'PromiseKit', '~> 6.8'
  pod 'GoogleWebRTC'
  pod 'CocoaMQTT'
  pod 'ReachabilitySwift'

end
